// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/hjc/demo/pb/demo.proto

public final class DemoProto {
  private DemoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Obj1OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 val1 = 1;
    /**
     * <code>required int32 val1 = 1;</code>
     */
    boolean hasVal1();
    /**
     * <code>required int32 val1 = 1;</code>
     */
    int getVal1();

    // repeated .Obj2 val2 = 2;
    /**
     * <code>repeated .Obj2 val2 = 2;</code>
     */
    java.util.List<DemoProto.Obj2> 
        getVal2List();
    /**
     * <code>repeated .Obj2 val2 = 2;</code>
     */
    DemoProto.Obj2 getVal2(int index);
    /**
     * <code>repeated .Obj2 val2 = 2;</code>
     */
    int getVal2Count();
    /**
     * <code>repeated .Obj2 val2 = 2;</code>
     */
    java.util.List<? extends DemoProto.Obj2OrBuilder> 
        getVal2OrBuilderList();
    /**
     * <code>repeated .Obj2 val2 = 2;</code>
     */
    DemoProto.Obj2OrBuilder getVal2OrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Obj1}
   */
  public static final class Obj1 extends
      com.google.protobuf.GeneratedMessage
      implements Obj1OrBuilder {
    // Use Obj1.newBuilder() to construct.
    private Obj1(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Obj1(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Obj1 defaultInstance;
    public static Obj1 getDefaultInstance() {
      return defaultInstance;
    }

    public Obj1 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Obj1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              val1_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                val2_ = new java.util.ArrayList<DemoProto.Obj2>();
                mutable_bitField0_ |= 0x00000002;
              }
              val2_.add(input.readMessage(DemoProto.Obj2.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          val2_ = java.util.Collections.unmodifiableList(val2_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DemoProto.internal_static_Obj1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DemoProto.internal_static_Obj1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DemoProto.Obj1.class, DemoProto.Obj1.Builder.class);
    }

    public static com.google.protobuf.Parser<Obj1> PARSER =
        new com.google.protobuf.AbstractParser<Obj1>() {
      public Obj1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Obj1(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Obj1> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 val1 = 1;
    public static final int VAL1_FIELD_NUMBER = 1;
    private int val1_;
    /**
     * <code>required int32 val1 = 1;</code>
     */
    public boolean hasVal1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 val1 = 1;</code>
     */
    public int getVal1() {
      return val1_;
    }

    // repeated .Obj2 val2 = 2;
    public static final int VAL2_FIELD_NUMBER = 2;
    private java.util.List<DemoProto.Obj2> val2_;
    /**
     * <code>repeated .Obj2 val2 = 2;</code>
     */
    public java.util.List<DemoProto.Obj2> getVal2List() {
      return val2_;
    }
    /**
     * <code>repeated .Obj2 val2 = 2;</code>
     */
    public java.util.List<? extends DemoProto.Obj2OrBuilder> 
        getVal2OrBuilderList() {
      return val2_;
    }
    /**
     * <code>repeated .Obj2 val2 = 2;</code>
     */
    public int getVal2Count() {
      return val2_.size();
    }
    /**
     * <code>repeated .Obj2 val2 = 2;</code>
     */
    public DemoProto.Obj2 getVal2(int index) {
      return val2_.get(index);
    }
    /**
     * <code>repeated .Obj2 val2 = 2;</code>
     */
    public DemoProto.Obj2OrBuilder getVal2OrBuilder(
        int index) {
      return val2_.get(index);
    }

    private void initFields() {
      val1_ = 0;
      val2_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVal1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getVal2Count(); i++) {
        if (!getVal2(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, val1_);
      }
      for (int i = 0; i < val2_.size(); i++) {
        output.writeMessage(2, val2_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, val1_);
      }
      for (int i = 0; i < val2_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, val2_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DemoProto.Obj1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoProto.Obj1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoProto.Obj1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoProto.Obj1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoProto.Obj1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DemoProto.Obj1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DemoProto.Obj1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DemoProto.Obj1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DemoProto.Obj1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DemoProto.Obj1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DemoProto.Obj1 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Obj1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DemoProto.Obj1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DemoProto.internal_static_Obj1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DemoProto.internal_static_Obj1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DemoProto.Obj1.class, DemoProto.Obj1.Builder.class);
      }

      // Construct using DemoProto.Obj1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getVal2FieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        val1_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (val2Builder_ == null) {
          val2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          val2Builder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DemoProto.internal_static_Obj1_descriptor;
      }

      public DemoProto.Obj1 getDefaultInstanceForType() {
        return DemoProto.Obj1.getDefaultInstance();
      }

      public DemoProto.Obj1 build() {
        DemoProto.Obj1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DemoProto.Obj1 buildPartial() {
        DemoProto.Obj1 result = new DemoProto.Obj1(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.val1_ = val1_;
        if (val2Builder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            val2_ = java.util.Collections.unmodifiableList(val2_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.val2_ = val2_;
        } else {
          result.val2_ = val2Builder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DemoProto.Obj1) {
          return mergeFrom((DemoProto.Obj1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DemoProto.Obj1 other) {
        if (other == DemoProto.Obj1.getDefaultInstance()) return this;
        if (other.hasVal1()) {
          setVal1(other.getVal1());
        }
        if (val2Builder_ == null) {
          if (!other.val2_.isEmpty()) {
            if (val2_.isEmpty()) {
              val2_ = other.val2_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureVal2IsMutable();
              val2_.addAll(other.val2_);
            }
            onChanged();
          }
        } else {
          if (!other.val2_.isEmpty()) {
            if (val2Builder_.isEmpty()) {
              val2Builder_.dispose();
              val2Builder_ = null;
              val2_ = other.val2_;
              bitField0_ = (bitField0_ & ~0x00000002);
              val2Builder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getVal2FieldBuilder() : null;
            } else {
              val2Builder_.addAllMessages(other.val2_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVal1()) {
          
          return false;
        }
        for (int i = 0; i < getVal2Count(); i++) {
          if (!getVal2(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DemoProto.Obj1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DemoProto.Obj1) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 val1 = 1;
      private int val1_ ;
      /**
       * <code>required int32 val1 = 1;</code>
       */
      public boolean hasVal1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 val1 = 1;</code>
       */
      public int getVal1() {
        return val1_;
      }
      /**
       * <code>required int32 val1 = 1;</code>
       */
      public Builder setVal1(int value) {
        bitField0_ |= 0x00000001;
        val1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 val1 = 1;</code>
       */
      public Builder clearVal1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        val1_ = 0;
        onChanged();
        return this;
      }

      // repeated .Obj2 val2 = 2;
      private java.util.List<DemoProto.Obj2> val2_ =
        java.util.Collections.emptyList();
      private void ensureVal2IsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          val2_ = new java.util.ArrayList<DemoProto.Obj2>(val2_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          DemoProto.Obj2, DemoProto.Obj2.Builder, DemoProto.Obj2OrBuilder> val2Builder_;

      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public java.util.List<DemoProto.Obj2> getVal2List() {
        if (val2Builder_ == null) {
          return java.util.Collections.unmodifiableList(val2_);
        } else {
          return val2Builder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public int getVal2Count() {
        if (val2Builder_ == null) {
          return val2_.size();
        } else {
          return val2Builder_.getCount();
        }
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public DemoProto.Obj2 getVal2(int index) {
        if (val2Builder_ == null) {
          return val2_.get(index);
        } else {
          return val2Builder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public Builder setVal2(
          int index, DemoProto.Obj2 value) {
        if (val2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVal2IsMutable();
          val2_.set(index, value);
          onChanged();
        } else {
          val2Builder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public Builder setVal2(
          int index, DemoProto.Obj2.Builder builderForValue) {
        if (val2Builder_ == null) {
          ensureVal2IsMutable();
          val2_.set(index, builderForValue.build());
          onChanged();
        } else {
          val2Builder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public Builder addVal2(DemoProto.Obj2 value) {
        if (val2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVal2IsMutable();
          val2_.add(value);
          onChanged();
        } else {
          val2Builder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public Builder addVal2(
          int index, DemoProto.Obj2 value) {
        if (val2Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVal2IsMutable();
          val2_.add(index, value);
          onChanged();
        } else {
          val2Builder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public Builder addVal2(
          DemoProto.Obj2.Builder builderForValue) {
        if (val2Builder_ == null) {
          ensureVal2IsMutable();
          val2_.add(builderForValue.build());
          onChanged();
        } else {
          val2Builder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public Builder addVal2(
          int index, DemoProto.Obj2.Builder builderForValue) {
        if (val2Builder_ == null) {
          ensureVal2IsMutable();
          val2_.add(index, builderForValue.build());
          onChanged();
        } else {
          val2Builder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public Builder addAllVal2(
          java.lang.Iterable<? extends DemoProto.Obj2> values) {
        if (val2Builder_ == null) {
          ensureVal2IsMutable();
          super.addAll(values, val2_);
          onChanged();
        } else {
          val2Builder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public Builder clearVal2() {
        if (val2Builder_ == null) {
          val2_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          val2Builder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public Builder removeVal2(int index) {
        if (val2Builder_ == null) {
          ensureVal2IsMutable();
          val2_.remove(index);
          onChanged();
        } else {
          val2Builder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public DemoProto.Obj2.Builder getVal2Builder(
          int index) {
        return getVal2FieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public DemoProto.Obj2OrBuilder getVal2OrBuilder(
          int index) {
        if (val2Builder_ == null) {
          return val2_.get(index);  } else {
          return val2Builder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public java.util.List<? extends DemoProto.Obj2OrBuilder> 
           getVal2OrBuilderList() {
        if (val2Builder_ != null) {
          return val2Builder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(val2_);
        }
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public DemoProto.Obj2.Builder addVal2Builder() {
        return getVal2FieldBuilder().addBuilder(
            DemoProto.Obj2.getDefaultInstance());
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public DemoProto.Obj2.Builder addVal2Builder(
          int index) {
        return getVal2FieldBuilder().addBuilder(
            index, DemoProto.Obj2.getDefaultInstance());
      }
      /**
       * <code>repeated .Obj2 val2 = 2;</code>
       */
      public java.util.List<DemoProto.Obj2.Builder> 
           getVal2BuilderList() {
        return getVal2FieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          DemoProto.Obj2, DemoProto.Obj2.Builder, DemoProto.Obj2OrBuilder> 
          getVal2FieldBuilder() {
        if (val2Builder_ == null) {
          val2Builder_ = new com.google.protobuf.RepeatedFieldBuilder<
              DemoProto.Obj2, DemoProto.Obj2.Builder, DemoProto.Obj2OrBuilder>(
                  val2_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          val2_ = null;
        }
        return val2Builder_;
      }

      // @@protoc_insertion_point(builder_scope:Obj1)
    }

    static {
      defaultInstance = new Obj1(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Obj1)
  }

  public interface Obj2OrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string subval1 = 1;
    /**
     * <code>required string subval1 = 1;</code>
     */
    boolean hasSubval1();
    /**
     * <code>required string subval1 = 1;</code>
     */
    java.lang.String getSubval1();
    /**
     * <code>required string subval1 = 1;</code>
     */
    com.google.protobuf.ByteString
        getSubval1Bytes();

    // optional double subval2 = 2;
    /**
     * <code>optional double subval2 = 2;</code>
     */
    boolean hasSubval2();
    /**
     * <code>optional double subval2 = 2;</code>
     */
    double getSubval2();
  }
  /**
   * Protobuf type {@code Obj2}
   */
  public static final class Obj2 extends
      com.google.protobuf.GeneratedMessage
      implements Obj2OrBuilder {
    // Use Obj2.newBuilder() to construct.
    private Obj2(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Obj2(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Obj2 defaultInstance;
    public static Obj2 getDefaultInstance() {
      return defaultInstance;
    }

    public Obj2 getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Obj2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              subval1_ = input.readBytes();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              subval2_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DemoProto.internal_static_Obj2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DemoProto.internal_static_Obj2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DemoProto.Obj2.class, DemoProto.Obj2.Builder.class);
    }

    public static com.google.protobuf.Parser<Obj2> PARSER =
        new com.google.protobuf.AbstractParser<Obj2>() {
      public Obj2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Obj2(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Obj2> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string subval1 = 1;
    public static final int SUBVAL1_FIELD_NUMBER = 1;
    private java.lang.Object subval1_;
    /**
     * <code>required string subval1 = 1;</code>
     */
    public boolean hasSubval1() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string subval1 = 1;</code>
     */
    public java.lang.String getSubval1() {
      java.lang.Object ref = subval1_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subval1_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string subval1 = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSubval1Bytes() {
      java.lang.Object ref = subval1_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subval1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional double subval2 = 2;
    public static final int SUBVAL2_FIELD_NUMBER = 2;
    private double subval2_;
    /**
     * <code>optional double subval2 = 2;</code>
     */
    public boolean hasSubval2() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional double subval2 = 2;</code>
     */
    public double getSubval2() {
      return subval2_;
    }

    private void initFields() {
      subval1_ = "";
      subval2_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSubval1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSubval1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, subval2_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSubval1Bytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, subval2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DemoProto.Obj2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoProto.Obj2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoProto.Obj2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoProto.Obj2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoProto.Obj2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DemoProto.Obj2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DemoProto.Obj2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DemoProto.Obj2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DemoProto.Obj2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DemoProto.Obj2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DemoProto.Obj2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Obj2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DemoProto.Obj2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DemoProto.internal_static_Obj2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DemoProto.internal_static_Obj2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DemoProto.Obj2.class, DemoProto.Obj2.Builder.class);
      }

      // Construct using DemoProto.Obj2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        subval1_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        subval2_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DemoProto.internal_static_Obj2_descriptor;
      }

      public DemoProto.Obj2 getDefaultInstanceForType() {
        return DemoProto.Obj2.getDefaultInstance();
      }

      public DemoProto.Obj2 build() {
        DemoProto.Obj2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DemoProto.Obj2 buildPartial() {
        DemoProto.Obj2 result = new DemoProto.Obj2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.subval1_ = subval1_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.subval2_ = subval2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DemoProto.Obj2) {
          return mergeFrom((DemoProto.Obj2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DemoProto.Obj2 other) {
        if (other == DemoProto.Obj2.getDefaultInstance()) return this;
        if (other.hasSubval1()) {
          bitField0_ |= 0x00000001;
          subval1_ = other.subval1_;
          onChanged();
        }
        if (other.hasSubval2()) {
          setSubval2(other.getSubval2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSubval1()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DemoProto.Obj2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DemoProto.Obj2) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string subval1 = 1;
      private java.lang.Object subval1_ = "";
      /**
       * <code>required string subval1 = 1;</code>
       */
      public boolean hasSubval1() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string subval1 = 1;</code>
       */
      public java.lang.String getSubval1() {
        java.lang.Object ref = subval1_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          subval1_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string subval1 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSubval1Bytes() {
        java.lang.Object ref = subval1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subval1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string subval1 = 1;</code>
       */
      public Builder setSubval1(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        subval1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string subval1 = 1;</code>
       */
      public Builder clearSubval1() {
        bitField0_ = (bitField0_ & ~0x00000001);
        subval1_ = getDefaultInstance().getSubval1();
        onChanged();
        return this;
      }
      /**
       * <code>required string subval1 = 1;</code>
       */
      public Builder setSubval1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        subval1_ = value;
        onChanged();
        return this;
      }

      // optional double subval2 = 2;
      private double subval2_ ;
      /**
       * <code>optional double subval2 = 2;</code>
       */
      public boolean hasSubval2() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double subval2 = 2;</code>
       */
      public double getSubval2() {
        return subval2_;
      }
      /**
       * <code>optional double subval2 = 2;</code>
       */
      public Builder setSubval2(double value) {
        bitField0_ |= 0x00000002;
        subval2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double subval2 = 2;</code>
       */
      public Builder clearSubval2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        subval2_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Obj2)
    }

    static {
      defaultInstance = new Obj2(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Obj2)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Obj1_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Obj1_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Obj2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Obj2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032com/hjc/demo/pb/demo.proto\")\n\004Obj1\022\014\n\004" +
      "val1\030\001 \002(\005\022\023\n\004val2\030\002 \003(\0132\005.Obj2\"(\n\004Obj2\022" +
      "\017\n\007subval1\030\001 \002(\t\022\017\n\007subval2\030\002 \001(\001B\013B\tDem" +
      "oProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Obj1_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Obj1_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Obj1_descriptor,
              new java.lang.String[] { "Val1", "Val2", });
          internal_static_Obj2_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Obj2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Obj2_descriptor,
              new java.lang.String[] { "Subval1", "Subval2", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
